LangString EV_TITLE ${LANG_SIMPCHINESE} 'EasyVideo 安装程序'
LangString EV_TITLE ${LANG_TRADCHINESE} 'EasyVideo 安裝程式'
LangString EV_TITLE ${LANG_ENGLISH} 'EasyVideo Setup'
LangString EV_TITLE ${LANG_JAPANESE} 'EasyVideo セットアップ'
LangString EV_TITLE ${LANG_KOREAN} 'EasyVideo 설치'
LangString EV_TITLE ${LANG_GERMAN} 'EasyVideo Setup'
LangString EV_TITLE ${LANG_FRENCH} 'EasyVideo Setup'
LangString EV_TITLE ${LANG_RUSSIAN} 'EasyVideo Setup'
LangString EV_TITLE ${LANG_SPANISH} 'EasyVideo Setup'
LangString EV_TITLE ${LANG_PORTUGUESEBR} 'EasyVideo Setup'
LangString EV_EXIST ${LANG_SIMPCHINESE} '检测到已安装的 EasyVideo，请选择要执行的操作。'
LangString EV_EXIST ${LANG_TRADCHINESE} '偵測到已安裝的 EasyVideo，請選擇操作。'
LangString EV_EXIST ${LANG_ENGLISH} 'An existing EasyVideo install was found. Choose an action.'
LangString EV_EXIST ${LANG_JAPANESE} 'EasyVideo が既にインストールされています。'
LangString EV_EXIST ${LANG_KOREAN} 'EasyVideo가 이미 설치되어 있습니다.'
LangString EV_EXIST ${LANG_GERMAN} 'EasyVideo ist bereits installiert.'
LangString EV_EXIST ${LANG_FRENCH} 'EasyVideo est deja installe.'
LangString EV_EXIST ${LANG_RUSSIAN} 'EasyVideo uzhe ustanovlen.'
LangString EV_EXIST ${LANG_SPANISH} 'EasyVideo ya esta instalado.'
LangString EV_EXIST ${LANG_PORTUGUESEBR} 'EasyVideo ja esta instalado.'
LangString EV_REINSTALL ${LANG_SIMPCHINESE} '重新安装（覆盖全部文件）'
LangString EV_REINSTALL ${LANG_TRADCHINESE} '重新安裝（覆寫全部檔案）'
LangString EV_REINSTALL ${LANG_ENGLISH} 'Reinstall (overwrite every file)'
LangString EV_REINSTALL ${LANG_JAPANESE} '再インストール'
LangString EV_REINSTALL ${LANG_KOREAN} '다시 설치'
LangString EV_REINSTALL ${LANG_GERMAN} 'Neu installieren'
LangString EV_REINSTALL ${LANG_FRENCH} 'Reinstaller'
LangString EV_REINSTALL ${LANG_RUSSIAN} 'Pereustanovit'
LangString EV_REINSTALL ${LANG_SPANISH} 'Reinstalar'
LangString EV_REINSTALL ${LANG_PORTUGUESEBR} 'Reinstalar'
LangString EV_REPAIR ${LANG_SIMPCHINESE} '修复（只补齐缺失或损坏的文件）'
LangString EV_REPAIR ${LANG_TRADCHINESE} '修復（只補齊缺少或損壞的檔案）'
LangString EV_REPAIR ${LANG_ENGLISH} 'Repair (only missing or damaged files)'
LangString EV_REPAIR ${LANG_JAPANESE} '修復'
LangString EV_REPAIR ${LANG_KOREAN} '복구'
LangString EV_REPAIR ${LANG_GERMAN} 'Reparieren'
LangString EV_REPAIR ${LANG_FRENCH} 'Reparer'
LangString EV_REPAIR ${LANG_RUSSIAN} 'Vosstanovit'
LangString EV_REPAIR ${LANG_SPANISH} 'Reparar'
LangString EV_REPAIR ${LANG_PORTUGUESEBR} 'Reparar'
LangString EV_REMOVE ${LANG_SIMPCHINESE} '卸载 EasyVideo'
LangString EV_REMOVE ${LANG_TRADCHINESE} '解除安裝 EasyVideo'
LangString EV_REMOVE ${LANG_ENGLISH} 'Uninstall EasyVideo'
LangString EV_REMOVE ${LANG_JAPANESE} 'アンインストール'
LangString EV_REMOVE ${LANG_KOREAN} '제거'
LangString EV_REMOVE ${LANG_GERMAN} 'Deinstallieren'
LangString EV_REMOVE ${LANG_FRENCH} 'Desinstaller'
LangString EV_REMOVE ${LANG_RUSSIAN} 'Udalit'
LangString EV_REMOVE ${LANG_SPANISH} 'Desinstalar'
LangString EV_REMOVE ${LANG_PORTUGUESEBR} 'Desinstalar'
LangString EV_WELCOME ${LANG_SIMPCHINESE} 'EasyVideo 将安装到当前用户目录，数据与日志分别保存在 data/ 与 log/。继续前请先关闭正在运行的 EasyVideo。'
LangString EV_WELCOME ${LANG_TRADCHINESE} 'EasyVideo 將安裝到目前使用者目錄，資料與日誌分別保存在 data/ 與 log/。'
LangString EV_WELCOME ${LANG_ENGLISH} 'EasyVideo installs into your user profile; data and logs live in data/ and log/. Close any running EasyVideo first.'
LangString EV_WELCOME ${LANG_JAPANESE} 'EasyVideo はユーザー領域にインストールされます。'
LangString EV_WELCOME ${LANG_KOREAN} 'EasyVideo는 사용자 폴더에 설치됩니다.'
LangString EV_WELCOME ${LANG_GERMAN} 'EasyVideo wird in Ihr Benutzerprofil installiert.'
LangString EV_WELCOME ${LANG_FRENCH} 'EasyVideo sinstalle dans votre profil utilisateur.'
LangString EV_WELCOME ${LANG_RUSSIAN} 'EasyVideo ustanavlivaetsya v profil polzovatelya.'
LangString EV_WELCOME ${LANG_SPANISH} 'EasyVideo se instala en su perfil de usuario.'
LangString EV_WELCOME ${LANG_PORTUGUESEBR} 'EasyVideo instala no seu perfil de usuario.'
LangString EV_SEC_MAIN ${LANG_SIMPCHINESE} 'EasyVideo 主程序（必需）'
LangString EV_SEC_MAIN ${LANG_TRADCHINESE} 'EasyVideo 主程式（必需）'
LangString EV_SEC_MAIN ${LANG_ENGLISH} 'EasyVideo core (required)'
LangString EV_SEC_MAIN ${LANG_JAPANESE} 'EasyVideo 本体'
LangString EV_SEC_MAIN ${LANG_KOREAN} 'EasyVideo 본체'
LangString EV_SEC_MAIN ${LANG_GERMAN} 'EasyVideo Kern'
LangString EV_SEC_MAIN ${LANG_FRENCH} 'EasyVideo coeur'
LangString EV_SEC_MAIN ${LANG_RUSSIAN} 'EasyVideo yadro'
LangString EV_SEC_MAIN ${LANG_SPANISH} 'EasyVideo principal'
LangString EV_SEC_MAIN ${LANG_PORTUGUESEBR} 'EasyVideo principal'
LangString EV_SEC_MENU ${LANG_SIMPCHINESE} '创建开始菜单快捷方式'
LangString EV_SEC_MENU ${LANG_TRADCHINESE} '建立開始功能表捷徑'
LangString EV_SEC_MENU ${LANG_ENGLISH} 'Create Start Menu shortcuts'
LangString EV_SEC_MENU ${LANG_JAPANESE} 'スタートメニューに作成'
LangString EV_SEC_MENU ${LANG_KOREAN} '시작 메뉴 만들기'
LangString EV_SEC_MENU ${LANG_GERMAN} 'Startmenue-Verknuepfungen'
LangString EV_SEC_MENU ${LANG_FRENCH} 'Raccourcis menu Demarrer'
LangString EV_SEC_MENU ${LANG_RUSSIAN} 'Sozdat yarlyki'
LangString EV_SEC_MENU ${LANG_SPANISH} 'Crear accesos'
LangString EV_SEC_MENU ${LANG_PORTUGUESEBR} 'Criar atalhos'
LangString EV_SEC_DESKTOP ${LANG_SIMPCHINESE} '创建桌面快捷方式'
LangString EV_SEC_DESKTOP ${LANG_TRADCHINESE} '建立桌面捷徑'
LangString EV_SEC_DESKTOP ${LANG_ENGLISH} 'Create a desktop shortcut'
LangString EV_SEC_DESKTOP ${LANG_JAPANESE} 'デスクトップに作成'
LangString EV_SEC_DESKTOP ${LANG_KOREAN} '바탕 화면 만들기'
LangString EV_SEC_DESKTOP ${LANG_GERMAN} 'Desktop-Verknuepfung'
LangString EV_SEC_DESKTOP ${LANG_FRENCH} 'Raccourci bureau'
LangString EV_SEC_DESKTOP ${LANG_RUSSIAN} 'Yarlyk na rabochem stole'
LangString EV_SEC_DESKTOP ${LANG_SPANISH} 'Acceso de escritorio'
LangString EV_SEC_DESKTOP ${LANG_PORTUGUESEBR} 'Atalho na area de trabalho'
LangString EV_SEC_PATH ${LANG_SIMPCHINESE} '把 ev 命令注册到 PATH'
LangString EV_SEC_PATH ${LANG_TRADCHINESE} '把 ev 命令註冊到 PATH'
LangString EV_SEC_PATH ${LANG_ENGLISH} 'Register the ev command on PATH'
LangString EV_SEC_PATH ${LANG_JAPANESE} 'ev コマンドを PATH に登録'
LangString EV_SEC_PATH ${LANG_KOREAN} 'ev 명령을 PATH에 등록'
LangString EV_SEC_PATH ${LANG_GERMAN} 'ev-Befehl in PATH'
LangString EV_SEC_PATH ${LANG_FRENCH} 'Commande ev dans PATH'
LangString EV_SEC_PATH ${LANG_RUSSIAN} 'Komanda ev v PATH'
LangString EV_SEC_PATH ${LANG_SPANISH} 'Comando ev en PATH'
LangString EV_SEC_PATH ${LANG_PORTUGUESEBR} 'Comando ev no PATH'
LangString EV_SEC_RUN ${LANG_SIMPCHINESE} '安装完成后启动 EasyVideo'
LangString EV_SEC_RUN ${LANG_TRADCHINESE} '安裝完成後啟動 EasyVideo'
LangString EV_SEC_RUN ${LANG_ENGLISH} 'Launch EasyVideo when done'
LangString EV_SEC_RUN ${LANG_JAPANESE} '完了後に起動'
LangString EV_SEC_RUN ${LANG_KOREAN} '완료 후 실행'
LangString EV_SEC_RUN ${LANG_GERMAN} 'Nach dem Setup starten'
LangString EV_SEC_RUN ${LANG_FRENCH} 'Lancer a la fin'
LangString EV_SEC_RUN ${LANG_RUSSIAN} 'Zapustit posle ustanovki'
LangString EV_SEC_RUN ${LANG_SPANISH} 'Ejecutar al terminar'
LangString EV_SEC_RUN ${LANG_PORTUGUESEBR} 'Executar ao terminar'
LangString EV_CACHE ${LANG_SIMPCHINESE} '正在解压安装包到缓存目录……'
LangString EV_CACHE ${LANG_TRADCHINESE} '正在解壓縮安裝包到快取目錄……'
LangString EV_CACHE ${LANG_ENGLISH} 'Extracting the package into the cache...'
LangString EV_CACHE ${LANG_JAPANESE} 'キャッシュへ展開中...'
LangString EV_CACHE ${LANG_KOREAN} '캐시로 푸는 중...'
LangString EV_CACHE ${LANG_GERMAN} 'Entpacke in den Cache...'
LangString EV_CACHE ${LANG_FRENCH} 'Extraction vers le cache...'
LangString EV_CACHE ${LANG_RUSSIAN} 'Raspakovka v kesh...'
LangString EV_CACHE ${LANG_SPANISH} 'Extrayendo a la cache...'
LangString EV_CACHE ${LANG_PORTUGUESEBR} 'Extraindo para o cache...'
LangString EV_COPY ${LANG_SIMPCHINESE} '正在安装文件……'
LangString EV_COPY ${LANG_TRADCHINESE} '正在安裝檔案……'
LangString EV_COPY ${LANG_ENGLISH} 'Installing files...'
LangString EV_COPY ${LANG_JAPANESE} 'ファイルを配置中...'
LangString EV_COPY ${LANG_KOREAN} '파일 설치 중...'
LangString EV_COPY ${LANG_GERMAN} 'Installiere Dateien...'
LangString EV_COPY ${LANG_FRENCH} 'Installation des fichiers...'
LangString EV_COPY ${LANG_RUSSIAN} 'Ustanovka faylov...'
LangString EV_COPY ${LANG_SPANISH} 'Instalando archivos...'
LangString EV_COPY ${LANG_PORTUGUESEBR} 'Instalando arquivos...'
LangString EV_HASH ${LANG_SIMPCHINESE} '正在写入文件校验值……'
LangString EV_HASH ${LANG_TRADCHINESE} '正在寫入檔案校驗值……'
LangString EV_HASH ${LANG_ENGLISH} 'Recording file hashes...'
LangString EV_HASH ${LANG_JAPANESE} 'ハッシュを記録中...'
LangString EV_HASH ${LANG_KOREAN} '해시 기록 중...'
LangString EV_HASH ${LANG_GERMAN} 'Schreibe Pruefsummen...'
LangString EV_HASH ${LANG_FRENCH} 'Enregistrement des empreintes...'
LangString EV_HASH ${LANG_RUSSIAN} 'Zapis kheshey...'
LangString EV_HASH ${LANG_SPANISH} 'Registrando hashes...'
LangString EV_HASH ${LANG_PORTUGUESEBR} 'Gravando hashes...'
LangString EV_DONE ${LANG_SIMPCHINESE} 'EasyVideo 安装完成。'
LangString EV_DONE ${LANG_TRADCHINESE} 'EasyVideo 安裝完成。'
LangString EV_DONE ${LANG_ENGLISH} 'EasyVideo is installed.'
LangString EV_DONE ${LANG_JAPANESE} 'EasyVideo の導入が完了しました。'
LangString EV_DONE ${LANG_KOREAN} 'EasyVideo 설치 완료.'
LangString EV_DONE ${LANG_GERMAN} 'EasyVideo ist installiert.'
LangString EV_DONE ${LANG_FRENCH} 'EasyVideo est installe.'
LangString EV_DONE ${LANG_RUSSIAN} 'EasyVideo ustanovlen.'
LangString EV_DONE ${LANG_SPANISH} 'EasyVideo esta instalado.'
LangString EV_DONE ${LANG_PORTUGUESEBR} 'EasyVideo foi instalado.'

Function .onInit
  ; 1) 先选语言。
  !insertmacro MUI_LANGDLL_DISPLAY
  ; 2) 检测已有安装，稍后询问重新安装 / 修复 / 卸载。
  StrCpy $EvMode 'full'
  StrCpy $EvExist '0'
  ReadRegStr $0 HKCU 'Software\EasyVideo' 'InstallDir'
  ${If} $0 != ''
    StrCpy $EvExist '1'
  ${EndIf}
FunctionEnd

Function EvExistingPage
  ${If} $EvExist != '1'
    Abort
  ${EndIf}
  !insertmacro MUI_HEADER_TEXT '$(EV_TITLE)' '$(EV_EXIST)'
  nsDialogs::Create 1018
  Pop $EvDlg
  ${If} $EvDlg == error
    Abort
  ${EndIf}
  ${NSD_CreateLabel} 0 0 100% 24u '$(EV_EXIST)'
  Pop $0
  ${NSD_CreateRadioButton} 0 30u 100% 12u '$(EV_REINSTALL)'
  Pop $EvRadioRe
  ${NSD_CreateRadioButton} 0 46u 100% 12u '$(EV_REPAIR)'
  Pop $EvRadioRep
  ${NSD_CreateRadioButton} 0 62u 100% 12u '$(EV_REMOVE)'
  Pop $EvRadioDel
  ${NSD_Check} $EvRadioRe
  nsDialogs::Show
FunctionEnd

Function EvExistingLeave
  ${NSD_GetState} $EvRadioRep $0
  ${If} $0 == ${BST_CHECKED}
    StrCpy $EvMode 'repair'
    Return
  ${EndIf}
  ${NSD_GetState} $EvRadioDel $0
  ${If} $0 == ${BST_CHECKED}
    StrCpy $EvMode 'remove'
  ${Else}
    StrCpy $EvMode 'full'
  ${EndIf}
FunctionEnd

Function EvLaunch
  ExecShell 'open' '$INSTDIR\app\EasyVideo.exe' '--open-delayed'
FunctionEnd

