/* EasyVideo - bake every runtime asset into one importable module.
 *
 * The packaged EXE ships no loose files, so this script compresses the web UI,
 * the raster icons and the PowerShell tray host into
 * src/server/assets.generated.js, which the HTTP layer imports.
 *
 * Keys are URL paths, so an HTTP request maps to a key by dropping the leading
 * slash:
 *
 *   /                      -> index.html
 *   /css/app.css            -> css/app.css
 *   /js/views/live.js       -> js/views/live.js
 *   /assets/icons/play.svg  -> assets/icons/play.svg
 *   /assets/img/icon-32.png -> assets/img/icon-32.png
 *
 * There is exactly ONE key per URL: src/web is walked first, then the root
 * assets/ tree, so the tray PNGs (which only exist under assets/img) are
 * reachable instead of falling through to the SPA shell.
 */

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import zlib from 'node:zlib';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const outFile = path.join(root, 'src', 'server', 'assets.generated.js');

const TYPES = [
  ['.html', 'text/html; charset=utf-8'],
  ['.js', 'text/javascript; charset=utf-8'],
  ['.mjs', 'text/javascript; charset=utf-8'],
  ['.css', 'text/css; charset=utf-8'],
  ['.json', 'application/json; charset=utf-8'],
  ['.svg', 'image/svg+xml'],
  ['.png', 'image/png'],
  ['.jpg', 'image/jpeg'],
  ['.jpeg', 'image/jpeg'],
  ['.gif', 'image/gif'],
  ['.webp', 'image/webp'],
  ['.ico', 'image/x-icon'],
  ['.woff2', 'font/woff2'],
  ['.ps1', 'text/plain; charset=utf-8'],
  ['.txt', 'text/plain; charset=utf-8'],
  ['.md', 'text/markdown; charset=utf-8']
];

export function mimeFor(file) {
  const lower = String(file || '').toLowerCase();
  for (const pair of TYPES) if (lower.endsWith(pair[0])) return pair[1];
  return 'application/octet-stream';
}

/** Recursively collect files; key = path relative to `base`, POSIX separators. */
function walk(dir, base, out) {
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(abs, base, out);
    else if (entry.isFile()) out.push({ abs, key: path.relative(base, abs).split(path.sep).join('/') });
  }
  return out;
}

function collect() {
  const files = [];
  const web = path.join(root, 'src', 'web');
  const assets = path.join(root, 'assets');
  // Web UI: index.html, css/*, js/**, assets/** (its own copy of the icons).
  walk(web, web, files);
  // Root assets tree: keyed as assets/img/* and assets/icons/* so the URL path
  // matches the key exactly. The web copy above wins when both exist.
  const webKeys = new Set(files.map((f) => f.key));
  const extra = [];
  walk(assets, root, extra);
  for (const f of extra) if (!webKeys.has(f.key)) files.push(f);
  // The tray host script lives with the server, not under web/.
  const tray = path.join(root, 'src', 'server', 'tray.ps1');
  if (fs.existsSync(tray)) files.push({ abs: tray, key: 'server/tray.ps1' });
  return files;
}

const isCompressible = (mime) =>
  mime.startsWith('text/') || mime.startsWith('application/json') ||
  mime.startsWith('application/javascript') || mime.startsWith('image/svg');

export function buildTable() {
  const table = {};
  let raw = 0;
  let stored = 0;
  for (const f of collect()) {
    const buf = fs.readFileSync(f.abs);
    raw += buf.length;
    const mime = mimeFor(f.abs);
    let gz = null;
    if (isCompressible(mime) && buf.length > 512) {
      const candidate = zlib.gzipSync(buf, { level: 9 });
      if (candidate.length < buf.length) gz = candidate;
    }
    const payload = gz || buf;
    stored += payload.length;
    table[f.key] = { mime, gz: !!gz, size: buf.length, data: payload.toString('base64') };
  }
  return { table, count: Object.keys(table).length, raw, stored };
}

export function writeModule() {
  const built = buildTable();
  const body = [
    '/* GENERATED by tools/gen-assets.mjs - do not edit by hand. */',
    '/* ' + built.count + ' assets, ' + Math.round(built.raw / 1024) + ' KiB raw -> ' + Math.round(built.stored / 1024) + ' KiB embedded. */',
    'export const EMBEDDED = ' + JSON.stringify(built.table) + ';',
    'export const EMBEDDED_COUNT = ' + built.count + ';',
    'export const EMBEDDED_BYTES = ' + built.raw + ';',
    'export default EMBEDDED;',
    ''
  ].join(String.fromCharCode(10));
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body, 'utf8');
  return built;
}

const selfPath = url.fileURLToPath(import.meta.url);
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(selfPath)) {
  const built = writeModule();
  const keys = Object.keys(built.table);
  console.log('embedded ' + built.count + ' assets -> ' + path.relative(root, outFile));
  console.log('  raw ' + Math.round(built.raw / 1024) + ' KiB, stored ' + Math.round(built.stored / 1024) + ' KiB');
  console.log('  tray keys: ' + keys.filter((k) => k.indexOf('tray') >= 0).join(' '));
}

export default { buildTable, writeModule, mimeFor };
