try { await import('../src/server/api.js'); console.log('ok   api.js'); } catch (e) { console.log('FAIL api.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/apps.js'); console.log('ok   apps.js'); } catch (e) { console.log('FAIL apps.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/archive.js'); console.log('ok   archive.js'); } catch (e) { console.log('FAIL archive.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/assets.generated.js'); console.log('ok   assets.generated.js'); } catch (e) { console.log('FAIL assets.generated.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/components.js'); console.log('ok   components.js'); } catch (e) { console.log('FAIL components.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/config.js'); console.log('ok   config.js'); } catch (e) { console.log('FAIL config.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/ffmpeg.js'); console.log('ok   ffmpeg.js'); } catch (e) { console.log('FAIL ffmpeg.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/http.js'); console.log('ok   http.js'); } catch (e) { console.log('FAIL http.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/hub.js'); console.log('ok   hub.js'); } catch (e) { console.log('FAIL hub.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/logger.js'); console.log('ok   logger.js'); } catch (e) { console.log('FAIL logger.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/main.js'); console.log('ok   main.js'); } catch (e) { console.log('FAIL main.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/paths.js'); console.log('ok   paths.js'); } catch (e) { console.log('FAIL paths.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/plugins.js'); console.log('ok   plugins.js'); } catch (e) { console.log('FAIL plugins.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/protocol.js'); console.log('ok   protocol.js'); } catch (e) { console.log('FAIL protocol.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/recommend.js'); console.log('ok   recommend.js'); } catch (e) { console.log('FAIL recommend.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/search.js'); console.log('ok   search.js'); } catch (e) { console.log('FAIL search.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/social.js'); console.log('ok   social.js'); } catch (e) { console.log('FAIL social.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/store.js'); console.log('ok   store.js'); } catch (e) { console.log('FAIL store.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/theme-routes.js'); console.log('ok   theme-routes.js'); } catch (e) { console.log('FAIL theme-routes.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/themes.js'); console.log('ok   themes.js'); } catch (e) { console.log('FAIL themes.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/transcode-routes.js'); console.log('ok   transcode-routes.js'); } catch (e) { console.log('FAIL transcode-routes.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/transport.js'); console.log('ok   transport.js'); } catch (e) { console.log('FAIL transport.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/tray.js'); console.log('ok   tray.js'); } catch (e) { console.log('FAIL tray.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/uploader.js'); console.log('ok   uploader.js'); } catch (e) { console.log('FAIL uploader.js :: ' + e.message.slice(0,110)); }
try { await import('../src/server/util.js'); console.log('ok   util.js'); } catch (e) { console.log('FAIL util.js :: ' + e.message.slice(0,110)); }