; EasyVideo installer - GENERATED by tools/package.mjs, do not edit by hand.
Unicode true
!include "MUI2.nsh"

Name "EasyVideo v1.0pre1"
OutFile "D:\dev\DeepSeekHarnessWorkspace\EasyVideo\installer\EasyVideo-v1.0pre1-Setup.exe"
InstallDir "$LOCALAPPDATA\\EasyVideo"
InstallDirRegKey HKCU "Software\\EasyVideo" "InstallDir"
RequestExecutionLevel user
SetCompressor /SOLID lzma
VIProductVersion "1.0.0.0"
VIAddVersionKey "ProductName" "EasyVideo"
VIAddVersionKey "FileDescription" "EasyVideo v1.0pre1 安装程序"
VIAddVersionKey "FileVersion" "1.0.0.0"
VIAddVersionKey "ProductVersion" "1.0.0.0"
VIAddVersionKey "CompanyName" "EasyVideo"
VIAddVersionKey "LegalCopyright" "EasyVideo"

!define MUI_ABORTWARNING
!define MUI_ICON "D:\dev\DeepSeekHarnessWorkspace\EasyVideo\assets\img\icon.ico"
!define MUI_UNICON "D:\dev\DeepSeekHarnessWorkspace\EasyVideo\assets\img\icon.ico"
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "SimpChinese"

Section "EasyVideo" SecMain
  SetOutPath "$INSTDIR"
  CreateDirectory "$INSTDIR\app"
  CreateDirectory "$INSTDIR\data"
  CreateDirectory "$INSTDIR\log"
  SetOutPath "$INSTDIR\app"
  File /oname=EasyVideo.exe "D:\dev\DeepSeekHarnessWorkspace\EasyVideo\app\EasyVideo.exe"
  File /oname=README.txt "D:\dev\DeepSeekHarnessWorkspace\EasyVideo\app\README.txt"
  SetOutPath "$INSTDIR"

  ; ev:// protocol for the current user, pointing at the installed exe.
  WriteRegStr HKCU "Software\Classes\ev" "" "URL:EasyVideo Protocol"
  WriteRegStr HKCU "Software\Classes\ev" "URL Protocol" ""
  WriteRegStr HKCU "Software\Classes\ev\DefaultIcon" "" "$INSTDIR\app\EasyVideo.exe,0"
  WriteRegStr HKCU "Software\Classes\ev\shell\open\command" "" "$INSTDIR\app\EasyVideo.exe %1"

  ; Add/Remove Programs entry.
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\EasyVideo" "DisplayName" "EasyVideo v1.0pre1"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\EasyVideo" "DisplayIcon" "$INSTDIR\app\EasyVideo.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\EasyVideo" "DisplayVersion" "v1.0pre1"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\EasyVideo" "Publisher" "EasyVideo"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\EasyVideo" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\EasyVideo" "NoModify" 1
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\EasyVideo" "NoRepair" 1
  WriteRegStr HKCU "Software\EasyVideo" "InstallDir" "$INSTDIR"

  WriteUninstaller "$INSTDIR\Uninstall.exe"
  CreateDirectory "$SMPROGRAMS\EasyVideo"
  CreateShortCut "$SMPROGRAMS\EasyVideo\EasyVideo.lnk" "$INSTDIR\app\EasyVideo.exe" "" "$INSTDIR\app\EasyVideo.exe" 0
  CreateShortCut "$SMPROGRAMS\EasyVideo\EasyVideo 数据目录.lnk" "$INSTDIR\data"
  CreateShortCut "$SMPROGRAMS\EasyVideo\EasyVideo 日志目录.lnk" "$INSTDIR\log"
  CreateShortCut "$DESKTOP\EasyVideo.lnk" "$INSTDIR\app\EasyVideo.exe" "" "$INSTDIR\app\EasyVideo.exe" 0
SectionEnd
Section "Uninstall" SecUninstall
  Delete "$DESKTOP\EasyVideo.lnk"
  Delete "$SMPROGRAMS\EasyVideo\*.lnk"
  RMDir "$SMPROGRAMS\EasyVideo"
  Delete "$INSTDIR\app\EasyVideo.exe"
  Delete "$INSTDIR\app\README.txt"
  RMDir "$INSTDIR\app"
  Delete "$INSTDIR\Uninstall.exe"
  ; data/ and log/ are intentionally preserved: user media lives there.
  DeleteRegKey HKCU "Software\Classes\ev"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\EasyVideo"
  DeleteRegKey HKCU "Software\EasyVideo"
  RMDir "$INSTDIR"
SectionEnd
